spring:
  application:
    name: hi
  profiles:
    active: "mysql"
resilience4j:
  ratelimiter:
    instances:
      backendApi:
        limit-for-period: 10 #numero de requests permitidos
        limit-refresh-period: 60s #tempo até o refresh dos tokens
        timeout-duration: 0s #tempo em que a trhead espera a disponibilidade de tokens antes de falhar